### ISSUE TITLE
OG bug: the skybox is distorted | Barkhang Monastery 

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#196]
Level 12, room 5.

_______________________

In OG, the skybox isn't properly drawn in one of the open sky rooms.  This issue is fixed in TR2Main, and TR2X would benefit from having a fix too.

![Screenshot](https://github.com/user-attachments/assets/834fa604-dc05-4f5f-a36d-5ceb8655f4b6)

It'll be worth checking if the skybox is properly drawn when viewed from each of the individual rooms marked in the image below.

![Screenshot](https://github.com/user-attachments/assets/74aa8499-c51b-4a45-83ae-2422f58e7ae2)

**Comment by lahm86** [comment]
Good catch. Room 5 needs this flag set to fix it, so a data thing at the end of the day. The other option is to instead always draw the skybox as is done in TR1X, rather than only for rooms with this flag; I wonder what TR2Main does.

![image](https://github.com/user-attachments/assets/a0356b6f-f2d8-4b10-80da-8eda180d54ba)

**Comment by Richard-L** [comment]
I remember reporting this to Arsunt in 2020 and he just said it's a "level design bug", basically how you've outlined already. He seemed to fix it quickly but sadly didn't post how.

**Comment by lahm86** [comment]
Found the commit:
https://github.com/Arsunt/TR2Main/commit/08aa3e9c0425691d788def2189cc6a134f6fc7e0
